version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #     - "9229:9229"  # Debug port
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5432/japanese_dictionary
  #     - NODE_ENV=development
  #     - DEBUG=*
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   tty: true
  #   stdin_open: true

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=japanese_dictionary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d japanese_dictionary"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: